services:
  web:
    environment:
      DB_HOST: db
      DB_PORT: "5432"
      DB_NAME: cafe_db
      DB_USER: postgres
      DB_PASSWORD: postgres

  db:
    environment:
      POSTGRES_DB: cafe_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
